on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          gemini-key: ${{ secrets.GEMINI_API_KEY }}
          model: 'gemini-2.0-flash'
          # max-length: 20000
          # model: '...'
          # thinking: dynamic
          # temperature: 0.0
          # prompt: 'You are helpful assistant is here to review the code. Please review the code change below and provide feedback.'
